import React,{useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowUpRight,Check,ChevronRight,CircleAlert,FileText,GitBranch,Plus,Search,Sparkles,Target,X}from'lucide-react';
import{starter}from'./data';import{decisionScore,scoreClaim,weakestClaim}from'./engine';import'./style.css';

function Meter({value}){return <div className="meter"><i style={{width:value+'%'}}/></div>}
function App(){
 const[data,setData]=useState(()=>JSON.parse(localStorage.getItem('proofweaver')||JSON.stringify(starter)));const[tab,setTab]=useState('map');const[selected,setSelected]=useState('c2');const[search,setSearch]=useState('');const[toast,setToast]=useState('');
 const save=d=>{setData(d);localStorage.setItem('proofweaver',JSON.stringify(d))};
 const ranked=useMemo(()=>[...data.options].map(o=>({...o,score:decisionScore(o,data.claims,data.evidence)})).sort((a,b)=>b.score-a.score),[data]);
 const weak=weakestClaim(data.claims,data.evidence),active=data.claims.find(c=>c.id===selected)||data.claims[0];
 const reset=()=>{save(starter);setToast('Demo restored');setTimeout(()=>setToast(''),1800)};
 const exportBrief=()=>{const top=ranked[0],txt=`DECISION BRIEF\n${data.question}\n\nRECOMMENDATION\n${top.name} â€” ${top.score}/100\n${top.desc}\n\nRATIONALE\n${data.claims.map(c=>`â€¢ ${c.text} (${scoreClaim(c,data.evidence).score}/100)`).join('\n')}\n\nWATCH ITEM\n${weak.text}\n`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:'text/plain'}));a.download='northstar-decision-brief.txt';a.click();setToast('Decision brief exported');setTimeout(()=>setToast(''),1800)};
 return <div className="app">
  <aside><div className="brand"><span><GitBranch/></span><b>Proofweaver</b></div><button className="new"><Plus/> New decision</button><nav><small>WORKSPACE</small>{[['map',GitBranch,'Evidence map'],['options',Target,'Options'],['brief',FileText,'Decision brief']].map(([id,I,l])=><button key={id} className={tab===id?'on':''} onClick={()=>setTab(id)}><I/>{l}{id==='map'&&<em>3</em>}</button>)}</nav><div className="recent"><small>RECENT</small><button className="active">Four-day workweek pilot<span>Updated now</span></button><button>European expansion<span>Yesterday</span></button><button>Vendor consolidation<span>3 days ago</span></button></div><div className="profile"><div>AM</div><span><b>Alex Morgan</b><small>Strategy workspace</small></span><button>...</button></div></aside>
  <main><header><div className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search evidence, claims, sourcesâ€¦"/></div><div className="avatars"><i>SK</i><i>JL</i><i>+3</i></div><button className="ghost" onClick={reset}>Reset demo</button><button className="primary" onClick={exportBrief}>Export brief <ArrowUpRight/></button></header>
  <section className="top"><div><div className="crumb">DECISIONS <ChevronRight/> OPERATIONS</div><h1>{data.question}</h1><p>{data.context}</p></div><div className="status"><span><i/> Analysis live</span><b>{data.evidence.length} sources</b><b>{data.claims.length} claims</b></div></section>
  {tab==='map'&&<><div className="insight"><Sparkles/><div><b>The case is promising, but one assumption needs attention.</b><p>Customer coverage is addressable. Incident response is the weakest part of the recommendation.</p></div><button onClick={()=>setSelected(weak.id)}>Review weak point <ChevronRight/></button></div>
  <div className="workspace"><div className="canvas"><div className="canvas-head"><div><h2>Reasoning map</h2><span>Evidence &rarr; claims &rarr; decision options</span></div><div className="legend"><i className="support"/>Supports <i className="challenge"/>Challenges</div></div><div className="columns"><div><label>EVIDENCE <span>{data.evidence.length}</span></label>{data.evidence.filter(e=>!search||JSON.stringify(e).toLowerCase().includes(search.toLowerCase())).map(e=><article className="evidence" key={e.id}><div className={e.stance}><Check/></div><div><b>{e.title}</b><small>{e.source}</small><p>{e.note}</p><footer><span>Quality {Math.round(e.quality*100)}</span><Meter value={e.quality*100}/></footer></div></article>)}</div><div><label>CLAIMS <span>{data.claims.length}</span></label>{data.claims.map(c=>{const s=scoreClaim(c,data.evidence);return <article key={c.id} onClick={()=>setSelected(c.id)} className={'claim '+(selected===c.id?'selected':'')}><div className="score"><b>{s.score}</b><small>/100</small></div><p>{c.text}</p><footer><span className={'confidence '+s.confidence.toLowerCase()}>{s.confidence} confidence</span><span>{c.evidence.length} links</span></footer></article>})}</div><div><label>OPTIONS <span>{ranked.length}</span></label>{ranked.map((o,i)=><article key={o.id} className={'option '+(!i?'winner':'')}><div className="rank">0{i+1}</div><div><b>{o.name}</b><p>{o.desc}</p><footer><Meter value={o.score}/><strong>{o.score}</strong></footer></div>{!i&&<span className="recommended">RECOMMENDED</span>}</article>)}</div></div></div>
  <aside className="inspector"><button className="close"><X/></button><small>CLAIM INSPECTOR</small><h3>{active.text}</h3>{(()=>{const s=scoreClaim(active,data.evidence);return <><div className="bigscore"><b>{s.score}</b><span>/100<br/><em>{s.confidence} confidence</em></span></div><Meter value={s.score}/></>})()}<h4>Linked evidence</h4>{active.evidence.map(id=>{const e=data.evidence.find(x=>x.id===id);return <div key={id} className="linked"><i className={e.stance}/><div><b>{e.title}</b><small>{e.stance==='supports'?'Supports':'Challenges'} this claim</small></div><span>{Math.round(e.quality*100)}</span></div>})}<div className="gap"><CircleAlert/><div><b>Evidence gap</b><p>Add weekend incident data to test whether rotating coverage is enough.</p></div></div><button className="add"><Plus/> Add supporting evidence</button></aside></div></>}
  {tab==='options'&&<div className="page"><h2>Compare options</h2><p>Weighted by the strength and relevance of every linked claim.</p>{ranked.map((o,i)=><article key={o.id} className="compare"><span>0{i+1}</span><div><h3>{o.name}</h3><p>{o.desc}</p></div><strong>{o.score}<small>/100</small></strong></article>)}</div>}
  {tab==='brief'&&<div className="page brief"><span className="eyebrow">DECISION BRIEF - DRAFT</span><h2>{ranked[0].name}</h2><p className="lead">Proceed with a contained 12-week pilot, protected by rotating coverage and measurable stop conditions.</p><h3>Why this direction</h3>{data.claims.map(c=><div key={c.id} className="rationale"><Check/><span>{c.text}</span><b>{scoreClaim(c,data.evidence).score}</b></div>)}<h3>Guardrail</h3><div className="warning"><CircleAlert/><p>Track Friday incident response weekly. Pause the pilot if median escalation time exceeds the existing threshold twice.</p></div><button className="primary" onClick={exportBrief}>Export decision brief <ArrowUpRight/></button></div>}
  </main>{toast&&<div className="toast"><Check/>{toast}</div>}
 </div>}
createRoot(document.getElementById('root')).render(<App/>);
