import React,{useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,ArrowUpRight,BrainCircuit,Check,ChevronRight,CircleAlert,FileText,GitBranch,LoaderCircle,Plus,RotateCcw,Search,ShieldCheck,Sparkles,Target,Upload,X}from'lucide-react';
import{starter,hydrateAnalysis}from'./data';import{buildDecisionBrief}from'./brief';import{decisionScore,readinessReport,scoreClaim,weakestClaim}from'./engine';import'./style.css';import'./v2.css';import'./accessibility.css';import'./commercial.css';

const clone=x=>JSON.parse(JSON.stringify(x));
function Meter({value}){return <div className="meter"><i style={{width:value+'%'}}/></div>}
function Modal({children,onClose,wide=false}){return <div className="backdrop"><div className={'modal '+(wide?'wide':'')} role="dialog" aria-modal="true"><button className="modal-x" aria-label="Close dialog" onClick={onClose}><X/></button>{children}</div></div>}
function App(){
 const[data,setData]=useState(()=>{try{return JSON.parse(localStorage.getItem('proofweaver-v2'))||clone(starter)}catch{return clone(starter)}});
 const[tab,setTab]=useState('map'),[selected,setSelected]=useState(data.claims[1]?.id),[search,setSearch]=useState(''),[toast,setToast]=useState(''),[compose,setCompose]=useState(false),[addEvidence,setAddEvidence]=useState(false),[loading,setLoading]=useState(false),[apiError,setApiError]=useState('');
 const[draft,setDraft]=useState({question:'',context:'',owner:'',reviewDate:'',sourceText:'',fileName:''});const fileRef=useRef();
 const save=d=>{setData(d);localStorage.setItem('proofweaver-v2',JSON.stringify(d))};
 const ranked=useMemo(()=>data.options.map(o=>({...o,score:decisionScore(o,data.claims,data.evidence)})).sort((a,b)=>b.score-a.score),[data]);
 const weak=weakestClaim(data.claims,data.evidence),active=data.claims.find(c=>c.id===selected)||data.claims[0],readiness=readinessReport(data);
 const flash=t=>{setToast(t);setTimeout(()=>setToast(''),2200)};
 const openNew=()=>{setDraft({question:'',context:'',owner:'',reviewDate:'',sourceText:'',fileName:''});setApiError('');setCompose(true)};
 const useDemo=()=>{save(clone(starter));setSelected(starter.claims[1].id);setCompose(false);setTab('map');flash('Demo workspace loaded')};
 const readFile=async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>500000) return setApiError('Please use a text file under 500 KB.');const text=await f.text();setDraft(d=>({...d,sourceText:text,fileName:f.name}));setApiError('')};
 const analyze=async()=>{if(!draft.question.trim()||!draft.sourceText.trim())return setApiError('Add a decision question and source material first.');setLoading(true);setApiError('');try{const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft)});const json=await res.json();if(!res.ok)throw new Error(json.error||'Analysis failed');const next=hydrateAnalysis(json,draft.question,draft.context,draft.sourceText,{owner:draft.owner,reviewDate:draft.reviewDate});save(next);setSelected(next.claims[0]?.id);setCompose(false);setTab('map');flash('GPT-5.6 analysis ready for review')}catch(e){setApiError(e.message)}finally{setLoading(false)}};
 const addManual=e=>{e.preventDefault();const form=new FormData(e.currentTarget),id=`e${Date.now()}`,claimId=form.get('claim'),evidence={id,title:form.get('title'),source:form.get('source')||'Manual evidence',note:form.get('excerpt'),quality:Number(form.get('quality'))/100,relevance:Number(form.get('relevance'))/100,stance:form.get('stance'),provenance:'human'};save({...data,evidence:[...data.evidence,evidence],claims:data.claims.map(c=>c.id===claimId?{...c,evidence:[...c.evidence,id]}:c)});setSelected(claimId);setAddEvidence(false);flash('Evidence linked and scores updated')};
 const exportBrief=()=>{const txt=buildDecisionBrief(data,ranked,readiness),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([txt],{type:'text/plain'}));a.download='proofweaver-decision-record.txt';a.click();flash('Decision record exported')};
 return <div className="app">
  <aside className="sidebar"><div className="brand"><span><GitBranch/></span><b>Proofweaver</b></div><button className="new" onClick={openNew}><Plus/> New decision</button><nav aria-label="Decision workspace"><small>WORKSPACE</small>{[['map',GitBranch,'Evidence map'],['options',Target,'Options'],['brief',FileText,'Decision brief']].map(([id,I,label])=><button key={id} className={tab===id?'on':''} onClick={()=>setTab(id)}><I/>{label}{id==='map'&&<em>{data.claims.length}</em>}</button>)}</nav><div className="recent"><small>CURRENT DECISION</small><button className="active">{data.question}<span>{data.evidence.length} sources · {data.claims.length} claims</span></button></div><div className="privacy"><ShieldCheck/><div><b>Private by design</b><span>Your API key stays server-side.</span></div></div><div className="profile"><div>PW</div><span><b>Decision workspace</b><small>Saved in this browser</small></span></div></aside>
  <main><header><div className="search"><Search/><input aria-label="Search workspace" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search evidence, claims, sources…"/></div><span className="model"><Sparkles/> GPT-5.6 analysis</span><button className="ghost" onClick={useDemo}><RotateCcw/> Reset demo</button><button className="primary" onClick={exportBrief}>Export brief <ArrowUpRight/></button></header>
   <section className="top"><div><div className="crumb">DECISIONS <ChevronRight/> ACTIVE REVIEW</div><h1>{data.question}</h1><p>{data.context}</p></div><div className="status"><span><i/> {readiness.score}% decision-ready</span><b>{data.evidence.length} sources</b><b>{data.claims.length} claims</b></div></section>
   {tab==='map'&&<><div className="insight"><Sparkles/><div><b>{data.summary}</b><p>Weakest assumption: {weak?.text}</p></div><button onClick={()=>setSelected(weak.id)}>Inspect weak point <ChevronRight/></button></div><div className="workspace"><div className="canvas"><div className="canvas-head"><div><h2>Reasoning map</h2><span>Evidence → claims → decision options</span></div><div className="canvas-actions"><span className="legend"><i className="support"/>Supports <i className="challenge"/>Challenges</span><button onClick={()=>setAddEvidence(true)}><Plus/> Evidence</button></div></div><div className="columns"><div><label>EVIDENCE <span>{data.evidence.length}</span></label>{data.evidence.filter(e=>!search||JSON.stringify(e).toLowerCase().includes(search.toLowerCase())).map(e=><article className="evidence" key={e.id}><div className={e.stance} aria-label={e.stance}>{e.stance==='supports'?<Check/>:<CircleAlert/>}</div><div><b>{e.title}</b><small>{e.source}</small><span className={'provenance '+(e.provenance||'unknown')}>{e.provenance==='human'?'Human added':e.provenance==='ai'?'GPT-5.6 extracted':'Verified demo'}</span><p>“{e.note}”</p><footer><span>Quality {Math.round(e.quality*100)}</span><Meter value={e.quality*100}/></footer></div></article>)}</div><div><label>CLAIMS <span>{data.claims.length}</span></label>{data.claims.map(c=>{const s=scoreClaim(c,data.evidence);return <button type="button" key={c.id} onClick={()=>setSelected(c.id)} aria-pressed={active?.id===c.id} className={'claim '+(active?.id===c.id?'selected':'')}><div className="score"><b>{s.score}</b><small>/100</small></div><p>{c.text}</p><footer><span className={'confidence '+s.confidence.toLowerCase()}>{s.confidence} confidence</span><span>{c.evidence.length} links</span></footer></button>})}</div><div><label>OPTIONS <span>{ranked.length}</span></label>{ranked.map((o,i)=><article key={o.id} className={'option '+(!i?'winner':'')}><div className="rank">0{i+1}</div><div><b>{o.name}</b><p>{o.desc}</p><footer><Meter value={o.score}/><strong>{o.score}</strong></footer></div>{!i&&<span className="recommended">RECOMMENDED</span>}</article>)}</div></div></div>
   {active&&<aside className="inspector"><small>CLAIM INSPECTOR</small><h3>{active.text}</h3>{(()=>{const s=scoreClaim(active,data.evidence);return <><div className="bigscore"><b>{s.score}</b><span>/100<br/><em>{s.confidence} confidence</em></span></div><Meter value={s.score}/></>})()}<h4>Linked evidence</h4>{active.evidence.map(id=>{const e=data.evidence.find(x=>x.id===id);return e&&<div key={id} className="linked"><i className={e.stance}/><div><b>{e.title}</b><small>{e.stance==='supports'?'Supports':'Challenges'} this claim</small></div><span>{Math.round(e.quality*100)}</span></div>})}<div className="gap"><CircleAlert/><div><b>Evidence gap</b><p>{data.gap}</p></div></div><button className="add" onClick={()=>setAddEvidence(true)}><Plus/> Add evidence</button></aside>}</div></>}
   {tab==='options'&&<div className="page"><span className="eyebrow">WEIGHTED COMPARISON</span><h2>Choose with the trade-offs visible</h2><p>Scores combine linked claim strength, claim importance, and option feasibility. They guide review—they do not replace judgment.</p>{ranked.map((o,i)=><article key={o.id} className="compare"><span>0{i+1}</span><div><h3>{o.name}</h3><p>{o.desc}</p><small>{o.claims.length} linked claims · {Math.round((o.feasibility||1)*100)}% feasibility factor</small></div><strong>{o.score}<small>/100</small></strong></article>)}</div>}
   {tab==='brief'&&<div className="page brief"><span className="eyebrow">DECISION BRIEF · READY TO EXPORT</span><h2>{ranked[0]?.name}</h2><p className="lead">{data.summary}</p><div className="accountability"><div><small>DECISION OWNER</small><b>{data.owner||'Unassigned'}</b></div><div><small>OUTCOME REVIEW</small><b>{data.reviewDate||'Not scheduled'}</b></div><div><small>READINESS</small><b>{readiness.score}%</b></div></div><h3>Decision readiness</h3><div className="readiness-grid">{readiness.gates.map(g=><div key={g.id} className={g.pass?'pass':'open'}>{g.pass?<Check/>:<CircleAlert/>}<span>{g.label}</span></div>)}</div><h3>Why this direction</h3>{data.claims.map(c=><div key={c.id} className="rationale"><Check/><span>{c.text}</span><b>{scoreClaim(c,data.evidence).score}</b></div>)}<h3>Guardrail</h3><div className="warning"><CircleAlert/><p>{data.guardrail}</p></div><button className="primary" onClick={exportBrief}>Export decision brief <ArrowUpRight/></button></div>}
  </main>
  {compose&&<Modal onClose={()=>!loading&&setCompose(false)} wide><div className="modal-icon"><BrainCircuit/></div><span className="eyebrow">NEW EVIDENCE REVIEW</span><h2>What decision are you facing?</h2><p>Paste notes, research, interview findings, or upload a text-based file. GPT-5.6 will extract an auditable map with verbatim evidence excerpts.</p><label>Decision question<input value={draft.question} onChange={e=>setDraft({...draft,question:e.target.value})} placeholder="Should we…?" autoFocus/></label><label>Context <span>optional</span><input value={draft.context} onChange={e=>setDraft({...draft,context:e.target.value})} placeholder="Who needs this decision, and by when?"/></label><div className="form-grid governance-fields"><label>Decision owner<input value={draft.owner} onChange={e=>setDraft({...draft,owner:e.target.value})} placeholder="Name or role"/></label><label>Outcome review date<input type="date" value={draft.reviewDate} onChange={e=>setDraft({...draft,reviewDate:e.target.value})}/></label></div><label>Source material<textarea value={draft.sourceText} onChange={e=>setDraft({...draft,sourceText:e.target.value})} placeholder="Paste reports, notes, data, or research here…"/></label><div className="upload-row"><input ref={fileRef} hidden type="file" accept=".txt,.md,.csv,.json" onChange={readFile}/><button className="upload" onClick={()=>fileRef.current.click()}><Upload/> {draft.fileName||'Upload TXT, MD, CSV, or JSON'}</button><span>{draft.sourceText.length.toLocaleString()} / 80,000 characters</span></div>{apiError&&<div className="api-error" role="alert"><CircleAlert/>{apiError}{apiError.includes('OPENAI_API_KEY')&&<small>Copy <b>.env.example</b> to <b>.env.local</b>, add your key, and restart the server.</small>}</div>}<div className="modal-actions"><button className="ghost" onClick={useDemo}>Explore demo instead</button><button className="primary analyze" disabled={loading} onClick={analyze}>{loading?<><LoaderCircle className="spin"/>Analyzing evidence…</>:<>Analyze with GPT-5.6 <ArrowRight/></>}</button></div></Modal>}
  {addEvidence&&<Modal onClose={()=>setAddEvidence(false)}><span className="eyebrow">HUMAN REVIEW</span><h2>Add and link evidence</h2><p>Add a source or counterexample the analysis missed. Linking it to a claim immediately recalculates the decision.</p><form onSubmit={addManual}><label>Link to claim<select required name="claim" defaultValue={active?.id}>{data.claims.map(c=><option key={c.id} value={c.id}>{c.text}</option>)}</select></label><label>Evidence title<input required name="title" placeholder="What did you learn?"/></label><label>Source<input name="source" placeholder="Report, interview, dataset…"/></label><label>Exact excerpt<textarea required name="excerpt" placeholder="Paste the supporting passage"/></label><div className="form-grid"><label>Stance<select name="stance"><option value="supports">Supports</option><option value="challenges">Challenges</option></select></label><label>Quality<input name="quality" type="number" defaultValue="80" min="0" max="100"/></label><label>Relevance<input name="relevance" type="number" defaultValue="80" min="0" max="100"/></label></div><div className="modal-actions"><button type="button" className="ghost" onClick={()=>setAddEvidence(false)}>Cancel</button><button className="primary" type="submit">Add to workspace <ArrowRight/></button></div></form></Modal>}
  {toast&&<div className="toast" role="status" aria-live="polite"><Check/>{toast}</div>}
 </div>
}
const root=globalThis.__proofweaverRoot??(globalThis.__proofweaverRoot=createRoot(document.getElementById('root')));
root.render(<App/>);
